{% set name = "pysmartdl" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pySmartDL-{{ version }}.tar.gz
  sha256: 35275d1694f3474d33bdca93b27d3608265ffd42f5aeb28e56f38b906c0c35f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pySmartDL
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/pySmartDL/
  summary: A Smart Download Manager for Python
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
